apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: ml
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mlflow-server
  template:
    metadata:
      labels:
        name: mlflow-server
    spec:
      serviceAccountName: mlflow
      volumes:
        - name: tls
          secret:
            secretName: mlflow-tls   # <-- autogenerato da OpenShift
      containers:
        - name: oauth-proxy
          image: registry.redhat.io/openshift4/ose-oauth-proxy:v4.12.0
          args:
            - --provider=openshift
            - --openshift-service-account=mlflow
            - --upstream=http://localhost:5000
            - --https-address=:8443
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --cookie-secret=SECRET
            - '--openshift-delegate-urls={"/": {"group":"route.openshift.io", "resource":"routes", "verb": "get", "namespace":"ml"}}'
            - '--openshift-sar={"verb":"get","resource":"routes","resourceAPIGroup":"route.openshift.io","namespace":"ml"}'
          ports:
            - containerPort: 8443
              name: https
          volumeMounts:
            - name: tls
              mountPath: /etc/tls/private

        - name: mlflow
          image: docker.io/hemaveeradhi/mlflow:amd64
          imagePullPolicy: IfNotPresent
          command: ["mlflow"]
          args:
            - server
            - --host
            - 0.0.0.0
            - --backend-store-uri
            - postgresql://admin:<pwd>@postgresql.ml.svc:5432/<db-name>?sslmode=disable
          ports:
            - containerPort: 5000
              protocol: TCP
